name: Deploy Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Create deployment package
      run: |
        cd src
        zip -r ../lambda_function.zip .
    
    - name: Deploy to AWS Lambda
      run: |
        aws lambda create-function \
          --function-name hello-world-lambda \
          --runtime python3.9 \
          --handler lambda_function.lambda_handler \
          --role ${{ secrets.AWS_LAMBDA_ROLE }} \
          --zip-file fileb://lambda_function.zip \
          || aws lambda update-function-code \
             --function-name hello-world-lambda \
             --zip-file fileb://lambda_function.zip
